apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-provider
  namespace: production        # Must match your Nginx deployment namespace
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"  # Set to "true" if using EKS Pod Identity; omit if using IRSA
    objects: |
      - objectName: "my-nginx-secret" # The exact name or ARN of your AWS secret
        objectType: "secretsmanager"