apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-karpenter-test
  labels:
    app: hpa-karpenter-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-karpenter-test
  template:
    metadata:
      labels:
        app: hpa-karpenter-test
    spec:
      nodeSelector:
        # force pods to run on on-demand nodes
        karpenter.sh/capacity-type: on-demand
      terminationGracePeriodSeconds: 30   # allow graceful shutdown
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"       # 0.5 vCPU per pod
              memory: "256Mi"   # 256MB per pod
            limits:
              cpu: "500m"
              memory: "256Mi"