apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hpa-karpenter-test-PDB
  namespace: default
spec:
  minAvailable: 3  # allow 2 out of 5 pods to be evicted at once
  selector:
    matchLabels:
      app: hpa-karpenter-test  # must match pod/deployment label