apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-manager-provider
  namespace: production        # Must match your Nginx deployment namespace
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"  # Set to "true" if using EKS Pod Identity; omit if using IRSA
    objects: |
      - objectName: "my-secret" # The exact name or ARN of your AWS secret
        objectType: "secretsmanager"
        jmesPath:
          - path: "MY_NGINX_PASSWORD"          # JSON key inside AWS Secrets Manager
            objectAlias: "MY_NGINX_PASSWORD"   # file name in the pod
