apiVersion: apps/v1
kind: Deployment
metadata:
  name: spot-test
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: spot-test
  template:
    metadata:
      labels:
        app: spot-test
    spec:
      nodeSelector:
        # force pods to run on spot nodes
        karpenter.sh/capacity-type: spot
      terminationGracePeriodSeconds: 30   # allow graceful shutdown
      containers:
      - name: nginx
        image: nginx:alpine
        ports: 
          - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi